# Generated by Django 4.1 on 2022-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplaylist',
            name='is_public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
